### ISSUE TITLE
Proper OG meta for docs

### ISSUE THREAD

**Issue by alvarosaburido** [asigloo/vue-dynamic-forms#280]
### Is your feature request related to a problem? Please describe.

Docs site https://vue-dynamic-forms.alvarosaburido.dev/ doesn't have proper OG data

### Describe the solution you'd like

Add meta tags 

### Describe alternatives you've considered

```
head:
  - - meta
    - property: og:title
      content: Hello

    - link
    - rel: preconnect
      href: https://test.com
```

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
